---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-httpd-deployment
  namespace: 3tier
spec:
  selector:
    matchLabels:
      app: web-httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: web-httpd
    spec:
      containers:
        - name: web-httpd
          image: httpd:2.4.55
          ports:
            - containerPort: 80