apiVersion: v1
kind: Service
metadata:
  name: web-httpd-service
  namespace: 3tier
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web-httpd
